### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by ghost** [okeuday/erlang_php#1]
Is it possible for you to put this library on [Composer/Packagist](https://packagist.org/), so that projects can require this library to encode and decode ETF?

**Comment by okeuday** [comment]
@CharlotteDunois it is added now at https://packagist.org/packages/okeuday/erlang_php .  It seems safest to not specify autoload information, but tell me if that is a problem.

**Comment by ghost** [comment]
It is a problem, as it's a really bad idea for someone to have to require the correct file himself, as composer generates an autoloader for every package that tells composer how it has to autoload it.

It seems that the autoloader is simply
```json
"autoload": {
    "psr-4": {
        "Erlang\\": ""
    }
}
```
(not tested but through previous experience with testing my own lib with composer deps led to that)

**Comment by okeuday** [comment]
@CharlotteDunois Ok, added the autoload as you have suggested.  Tell me if you have problems with it, but it seems like it should be fine then.

**Comment by ghost** [comment]
Sorry to bother you again, but I've tested it and needed is a different autoloader. 😛
```
"autoload": {
    "files": ["Erlang.php"]
}
```

**Comment by okeuday** [comment]
@CharlotteDunois No problem, I was wondering if the file namespace would be an issue but didn't find information related to that within the docs I was looking at.  The package is updated now so it should be fine, but tell me if you have further issues.
